<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class User extends Seeder
{
	public function run()
	{
		$data = [
			[
				'nis'  => '123456',
				'nama'  =>  'Dr. Agung Purnama, S.pd',
				'jenis_kelamin'  =>  'laki-laki',
				'alamat'  =>  'Morioh Morioh Cho Cho',
				'gambar' => 'default.png',
				'no_telp'  =>  '08291758869123',
				'username' => '123456',
				'password' => 'gurubk',
				'role' => 'guru',
			],
			[
				'nis'  => '12345',
				'nama'  =>  'Ilham Muzaqqi',
				'jenis_kelamin'  =>  'laki-laki',
				'kelas'  =>  'XII',
				'jurusan'  =>  'RPL',
				'rombel'  =>  'A',
				'tanggal_lahir'  =>  '2021-02-09',
				'alamat'  =>  'Yare Yare Dawa',
				'gambar' => 'default.png',
				'no_telp'  =>  '08291758869',
				'username' => '12345',
				'password' => 'siswasiswa',
				'role' => 'siswa',
			],
			[
				'nis'  => '18319831',
				'nama'  =>  'Jotaro Kujo',
				'jenis_kelamin'  =>  'laki-laki',
				'kelas'  =>  'XIII',
				'jurusan'  =>  'TEI',
				'rombel'  =>  'B',
				'tanggal_lahir'  =>  '1980-06-11',
				'alamat'  =>  'Jepang',
				'gambar' => 'default.png',
				'no_telp'  =>  '08319173131',
				'username' => '18319831',
				'password' => 'kujojotaro',
				'role' => 'siswa',
			],
			[
				'nis'  => '1793131',
				'nama'  =>  'Joseph Joestar',
				'jenis_kelamin'  =>  'laki-laki',
				'kelas'  =>  'XI',
				'jurusan'  =>  'TOI',
				'rombel'  =>  'C',
				'tanggal_lahir'  =>  '1946-08-15',
				'alamat'  =>  'Amerika',
				'gambar' => 'default.png',
				'no_telp'  =>  '08765927421',
				'username' => '1793131',
				'password' => 'josephkun',
				'role' => 'siswa',
			],
			[
				'nis'  => '19841741',
				'nama'  =>  'Jonathan Joestar',
				'jenis_kelamin'  =>  'laki-laki',
				'kelas'  =>  'XI',
				'jurusan'  =>  'SIJA',
				'rombel'  =>  'B',
				'tanggal_lahir'  =>  '1901-02-27',
				'alamat'  =>  'London',
				'gambar' => 'default.png',
				'no_telp'  =>  '08577164141',
				'username' => '19841741',
				'password' => 'jonathanjoestar',
				'role' => 'siswa',
			],
			[
				'nis'  => '167184151',
				'nama'  =>  'Josuke Higashikata',
				'jenis_kelamin'  =>  'laki-laki',
				'kelas'  =>  'X',
				'jurusan'  =>  'TEDK',
				'rombel'  =>  'A',
				'tanggal_lahir'  =>  '1990-11-07',
				'alamat'  =>  'Morioh',
				'gambar' => 'default.png',
				'no_telp'  =>  '0841646181',
				'username' => '167184151',
				'password' => 'josukerambutjelek',
				'role' => 'siswa',
			],
			[
				'nis'  => '191713131',
				'nama'  =>  'Giorno Giovanna',
				'jenis_kelamin'  =>  'laki-laki',
				'kelas'  =>  'XI',
				'jurusan'  =>  'PFPT',
				'rombel'  =>  'A',
				'tanggal_lahir'  =>  '2001-07-05',
				'alamat'  =>  'Italia',
				'gambar' => 'default.png',
				'no_telp'  =>  '089137316131',
				'username' => '191713131',
				'password' => 'giornopirang',
				'role' => 'siswa',
			],
			[
				'nis'  => '201846113',
				'nama'  =>  'Jolyne Kujo',
				'jenis_kelamin'  =>  'perempuan',
				'kelas'  =>  'X',
				'jurusan'  =>  'RPL',
				'rombel'  =>  'B',
				'tanggal_lahir'  =>  '2011-12-21',
				'alamat'  =>  'Amerika',
				'gambar' => 'default.png',
				'no_telp'  =>  '08551716131',
				'username' => '201846113',
				'password' => 'jolynekujo',
				'role' => 'siswa',
			],
			[
				'nis'  => '173917571',
				'nama'  =>  'Mikasa Ackerman',
				'jenis_kelamin'  =>  'perempuan',
				'kelas'  =>  'X',
				'jurusan'  =>  'TPTU',
				'rombel'  =>  'A',
				'tanggal_lahir'  =>  '2007-07-17',
				'alamat'  =>  'Paradis',
				'gambar' => 'default.png',
				'no_telp'  =>  '081747174189',
				'username' => '173917571',
				'password' => 'mikasaackerman',
				'role' => 'siswa',
			],
			[
				'nis'  => '19581641741',
				'nama'  =>  'Annie Leonhart',
				'jenis_kelamin'  =>  'perempuan',
				'kelas'  =>  'X',
				'jurusan'  =>  'IOP',
				'rombel'  =>  'A',
				'tanggal_lahir'  =>  '2005-11-05',
				'alamat'  =>  'Marley',
				'gambar' => 'default.png',
				'no_telp'  =>  '084671647191',
				'username' => '19581641741',
				'password' => 'annieleonhart',
				'role' => 'siswa',
			],
			[
				'nis'  => '1859916561',
				'nama'  =>  'Ani Pemberani',
				'jenis_kelamin'  =>  'perempuan',
				'kelas'  =>  'XII',
				'jurusan'  =>  'TEI',
				'rombel'  =>  'A',
				'tanggal_lahir'  =>  '1976-12-17',
				'alamat'  =>  'Indonesia',
				'gambar' => 'default.png',
				'no_telp'  =>  '0875817411316',
				'username' => '1859916561',
				'password' => 'anipemberani',
				'role' => 'siswa',
			],
			[
				'nis'  => '1957195715',
				'nama'  =>  'Uraraka Ochaco',
				'jenis_kelamin'  =>  'perempuan',
				'kelas'  =>  'XIII',
				'jurusan'  =>  'RPL',
				'rombel'  =>  'A',
				'tanggal_lahir'  =>  '2012-09-25',
				'alamat'  =>  'Jepang',
				'gambar' => 'default.png',
				'no_telp'  =>  '089716481931',
				'username' => '1957195715',
				'password' => 'urarakaochaco',
				'role' => 'siswa',
			]
		];
		$this->db->table('user')->insertBatch($data);
	}
}
